import type { Investor } from "./types";

export const INVESTORS: Investor[] = [
  {
    id: "inv_kestrel",
    slug: "kestrel-ventures",
    name: "Amara Chen",
    type: "vc",
    firm: "Kestrel Ventures",
    title: "General Partner",
    bio: "Amara leads seed and Series A investing at Kestrel, focused on AI infrastructure and healthtech. Previously built and sold a clinical data platform.",
    country: "United States",
    city: "San Francisco",
    hue: 210,
    industries: ["ai", "healthtech", "saas"],
    stages: ["seed", "series_a"],
    avgCheque: "$1.5M – $4M",
    portfolioCount: 34,
    avgResponseTime: "1 day",
    verified: true,
    rating: 4.9,
    founderFeedback: [
      {
        quote:
          "Amara gave us term-sheet feedback within 48 hours and never wasted a meeting.",
        author: "Priya Nandakumar",
        startup: "Orbital Health",
      },
    ],
    portfolioSlugs: ["orbital-health", "glasswing-ai", "pathwise"],
  },
  {
    id: "inv_northbridge",
    slug: "northbridge-capital",
    name: "David Okafor",
    type: "vc",
    firm: "Northbridge Capital",
    title: "Partner",
    bio: "David invests in fintech and B2B infrastructure at Series A and B, with a focus on companies selling into regulated industries.",
    country: "United Kingdom",
    city: "London",
    hue: 205,
    industries: ["fintech", "cybersecurity", "logistics"],
    stages: ["series_a", "series_b"],
    avgCheque: "$4M – $12M",
    portfolioCount: 21,
    avgResponseTime: "3 days",
    verified: true,
    rating: 4.7,
    founderFeedback: [
      {
        quote: "Sharp diligence, but he closes fast once convinced.",
        author: "Noa Rosen",
        startup: "Cipherline",
      },
    ],
    portfolioSlugs: ["ledgerly", "cipherline", "northtide"],
  },
  {
    id: "inv_sarah",
    slug: "sarah-lindqvist",
    name: "Sarah Lindqvist",
    type: "angel",
    firm: "Independent",
    title: "Angel Investor",
    bio: "Former VP of Engineering at a unicorn logistics company. Writes early checks into hardware and climate startups she can personally help recruit for.",
    country: "Sweden",
    city: "Stockholm",
    hue: 145,
    industries: ["climatetech", "robotics", "deeptech"],
    stages: ["pre_seed", "seed"],
    avgCheque: "$25K – $100K",
    portfolioCount: 18,
    avgResponseTime: "2 days",
    verified: true,
    rating: 4.8,
    founderFeedback: [
      {
        quote:
          "Sarah introduced us to our first two enterprise design partners personally.",
        author: "Elin Bjornsson",
        startup: "Verdant Carbon",
      },
    ],
    portfolioSlugs: ["verdant-carbon", "meridian-robotics", "fablume"],
  },
  {
    id: "inv_meridian_capital",
    slug: "meridian-family-office",
    name: "Thomas Whitfield",
    type: "family_office",
    firm: "Whitfield Family Office",
    title: "Investment Director",
    bio: "Deploys patient, multi-generational capital into proptech, logistics and healthtech, with a preference for founders building for the long term.",
    country: "United States",
    city: "Boston",
    hue: 26,
    industries: ["proptech", "logistics", "healthtech"],
    stages: ["series_a", "series_b", "growth"],
    avgCheque: "$3M – $10M",
    portfolioCount: 12,
    avgResponseTime: "5 days",
    verified: true,
    rating: 4.6,
    founderFeedback: [
      {
        quote:
          "No pressure for a fast exit — genuinely aligned with building for a decade.",
        author: "Brian Alvarez",
        startup: "Realmark",
      },
    ],
    portfolioSlugs: ["realmark", "kindlecare"],
  },
  {
    id: "inv_publicfund",
    slug: "gulf-innovation-fund",
    name: "Layla Haddad",
    type: "government",
    firm: "Gulf Innovation Fund",
    title: "Programme Lead",
    bio: "Manages a government-backed co-investment fund supporting deep tech and climate startups relocating to or expanding in the region.",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    hue: 178,
    industries: ["climatetech", "deeptech", "space"],
    stages: ["seed", "series_a"],
    avgCheque: "$500K – $3M",
    portfolioCount: 27,
    avgResponseTime: "7 days",
    verified: true,
    rating: 4.4,
    founderFeedback: [
      {
        quote:
          "The co-investment matching made our round come together two weeks faster.",
        author: "Grace Okonjo",
        startup: "Quivera Space",
      },
    ],
    portfolioSlugs: ["quivera-space", "verdant-carbon"],
  },
  {
    id: "inv_priya_v",
    slug: "priya-varma",
    name: "Priya Varma",
    type: "angel",
    firm: "Independent",
    title: "Angel Investor",
    bio: "Operator angel and former Head of Growth at two Series C startups. Focused on consumer, edtech and marketplace businesses.",
    country: "India",
    city: "Mumbai",
    hue: 42,
    industries: ["edtech", "consumer", "marketplace"],
    stages: ["pre_seed", "seed"],
    avgCheque: "$15K – $75K",
    portfolioCount: 22,
    avgResponseTime: "1 day",
    verified: true,
    rating: 4.9,
    founderFeedback: [
      {
        quote:
          "Priya rewrote our onboarding funnel copy herself on a Sunday. Rare operator energy.",
        author: "Ananya Rao",
        startup: "Pathwise",
      },
    ],
    portfolioSlugs: ["pathwise"],
  },
  {
    id: "inv_harborcrest",
    slug: "harborcrest-partners",
    name: "Michael Stein",
    type: "vc",
    firm: "Harborcrest Partners",
    title: "Managing Partner",
    bio: "Leads growth-stage investing across fintech and enterprise software, typically joining as a founder's first institutional board member.",
    country: "United States",
    city: "New York",
    hue: 152,
    industries: ["fintech", "saas", "ai"],
    stages: ["series_b", "series_c", "growth"],
    avgCheque: "$8M – $25M",
    portfolioCount: 16,
    avgResponseTime: "4 days",
    verified: true,
    rating: 4.5,
    founderFeedback: [
      {
        quote:
          "Michael pushed back hard in diligence but it made our Series B pitch bulletproof.",
        author: "Adaeze Okoro",
        startup: "Ledgerly",
      },
    ],
    portfolioSlugs: ["ledgerly", "realmark"],
  },
  {
    id: "inv_yuki",
    slug: "yuki-tanaka",
    name: "Yuki Tanaka",
    type: "angel",
    firm: "Independent",
    title: "Angel Investor",
    bio: "Early engineer at a major cybersecurity company, now writes technical due-diligence-led checks into security and infrastructure startups.",
    country: "Japan",
    city: "Tokyo",
    hue: 12,
    industries: ["cybersecurity", "ai", "deeptech"],
    stages: ["seed", "series_a"],
    avgCheque: "$30K – $120K",
    portfolioCount: 14,
    avgResponseTime: "2 days",
    verified: true,
    rating: 4.7,
    founderFeedback: [
      {
        quote:
          "The most technically rigorous angel we spoke to, and the fastest to decide.",
        author: "Itai Ben-David",
        startup: "Cipherline",
      },
    ],
    portfolioSlugs: ["cipherline", "glasswing-ai"],
  },
  {
    id: "inv_riverstone",
    slug: "riverstone-accel-fund",
    name: "Claire Dubois",
    type: "vc",
    firm: "Riverstone Ventures",
    title: "Principal",
    bio: "Backs pre-seed and seed founders across Europe, with a soft spot for hardware and climate teams tackling unglamorous infrastructure problems.",
    country: "France",
    city: "Paris",
    hue: 88,
    industries: ["climatetech", "deeptech", "robotics"],
    stages: ["pre_seed", "seed"],
    avgCheque: "$300K – $1.2M",
    portfolioCount: 19,
    avgResponseTime: "2 days",
    verified: false,
    rating: 4.3,
    founderFeedback: [
      {
        quote:
          "Claire understood our hardware timeline better than most technical investors do.",
        author: "Lukas Vogt",
        startup: "Fablume",
      },
    ],
    portfolioSlugs: ["fablume", "meridian-robotics"],
  },
  {
    id: "inv_founders_bay",
    slug: "founders-bay-capital",
    name: "Diego Morales",
    type: "vc",
    firm: "Founders Bay Capital",
    title: "General Partner",
    bio: "Invests across gaming, consumer and marketplace businesses, joining as lead or co-lead at seed through Series A.",
    country: "United States",
    city: "Los Angeles",
    hue: 350,
    industries: ["gaming", "consumer", "media"],
    stages: ["pre_seed", "seed", "series_a"],
    avgCheque: "$500K – $2.5M",
    portfolioCount: 25,
    avgResponseTime: "3 days",
    verified: true,
    rating: 4.6,
    founderFeedback: [
      {
        quote:
          "Diego watched our alpha gameplay footage before the first call. Rare prep.",
        author: "Ji-hoon Park",
        startup: "Ninefold Games",
      },
    ],
    portfolioSlugs: ["ninefold-games"],
  },
];

export function getInvestorBySlug(slug: string): Investor | undefined {
  return INVESTORS.find((investor) => investor.slug === slug);
}
