import type { AppNotification } from "./types";

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    type: "meeting",
    actorName: "Amara Chen",
    actorHue: 210,
    message: "requested a meeting for Thursday at 2:00 PM",
    createdAt: "2026-08-03T08:10:00Z",
    read: false,
  },
  {
    id: "n2",
    type: "match",
    actorName: "Conditor",
    actorHue: 220,
    message: "found 3 new investor matches above 90% fit",
    createdAt: "2026-08-03T06:00:00Z",
    read: false,
  },
  {
    id: "n3",
    type: "view",
    actorName: "David Okafor",
    actorHue: 205,
    message: "viewed your pitch deck",
    createdAt: "2026-08-02T19:40:00Z",
    read: false,
  },
  {
    id: "n4",
    type: "save",
    actorName: "Sarah Lindqvist",
    actorHue: 145,
    message: "saved your startup profile",
    createdAt: "2026-08-02T17:05:00Z",
    read: true,
  },
  {
    id: "n5",
    type: "message",
    actorName: "Layla Haddad",
    actorHue: 178,
    message: "sent you a message about co-investment matching",
    createdAt: "2026-08-01T11:15:00Z",
    read: true,
  },
  {
    id: "n6",
    type: "milestone",
    actorName: "Conditor",
    actorHue: 220,
    message: "flagged that your investment readiness score increased to 86",
    createdAt: "2026-07-30T09:00:00Z",
    read: true,
  },
  {
    id: "n7",
    type: "system",
    actorName: "Conditor",
    actorHue: 220,
    message: "finished processing your pitch deck — it's ready for review",
    createdAt: "2026-07-28T13:22:00Z",
    read: true,
  },
];
