import type { Application, Cohort, Mentor } from "./types";

export const APPLICATIONS: Application[] = [
  {
    id: "app_1",
    startupName: "Solstice Analytics",
    founderName: "Renata Costa",
    industry: "ai",
    stage: "pre_seed",
    submittedAt: "2026-08-01T10:00:00Z",
    status: "interview",
    fitScore: 91,
  },
  {
    id: "app_2",
    startupName: "Pulsegrid",
    founderName: "Oliver Hansen",
    industry: "energy",
    stage: "seed",
    submittedAt: "2026-07-30T14:20:00Z",
    status: "reviewing",
    fitScore: 84,
  },
  {
    id: "app_3",
    startupName: "Cascade Biotech",
    founderName: "Ines Fischer",
    industry: "biotech",
    stage: "pre_seed",
    submittedAt: "2026-07-29T09:15:00Z",
    status: "pending",
    fitScore: 76,
  },
  {
    id: "app_4",
    startupName: "Lumen Robotics",
    founderName: "Kwame Asante",
    industry: "robotics",
    stage: "seed",
    submittedAt: "2026-07-28T16:40:00Z",
    status: "accepted",
    fitScore: 95,
  },
  {
    id: "app_5",
    startupName: "Fernway",
    founderName: "Bianca Silva",
    industry: "agritech",
    stage: "pre_seed",
    submittedAt: "2026-07-27T11:00:00Z",
    status: "reviewing",
    fitScore: 68,
  },
  {
    id: "app_6",
    startupName: "Doverside",
    founderName: "Hassan Malik",
    industry: "logistics",
    stage: "seed",
    submittedAt: "2026-07-25T13:30:00Z",
    status: "rejected",
    fitScore: 42,
  },
  {
    id: "app_7",
    startupName: "Aurora Vision",
    founderName: "Nadia Petrova",
    industry: "ai",
    stage: "seed",
    submittedAt: "2026-07-24T08:00:00Z",
    status: "interview",
    fitScore: 88,
  },
];

export const MENTORS: Mentor[] = [
  {
    id: "men_1",
    name: "Rachel Kim",
    expertise: ["Marketing & sales", "Business software"],
    hue: 210,
    sessionsThisMonth: 12,
  },
  {
    id: "men_2",
    name: "Omar Farouk",
    expertise: ["Fundraising", "Deal offers"],
    hue: 205,
    sessionsThisMonth: 9,
  },
  {
    id: "men_3",
    name: "Bethany Cole",
    expertise: ["Product", "AI"],
    hue: 145,
    sessionsThisMonth: 15,
  },
  {
    id: "men_4",
    name: "Marco Rinaldi",
    expertise: ["Hardware", "Supply chain"],
    hue: 26,
    sessionsThisMonth: 6,
  },
  {
    id: "men_5",
    name: "Sophie Dubois",
    expertise: ["Legal", "Regulatory"],
    hue: 178,
    sessionsThisMonth: 8,
  },
];

export const COHORTS: Cohort[] = [
  {
    id: "cohort_2026a",
    name: "Cohort 2026-A",
    programName: "Core Cohort",
    startDate: "2026-03-01",
    companies: [
      { name: "Lumen Robotics", industry: "robotics", hue: 210, progress: 78 },
      { name: "Aurora Vision", industry: "ai", hue: 205, progress: 64 },
      { name: "Nimbus Health", industry: "healthtech", hue: 330, progress: 91 },
      { name: "Fieldstone", industry: "agritech", hue: 88, progress: 52 },
      { name: "Vantagepoint", industry: "fintech", hue: 152, progress: 70 },
      { name: "Cliffside Security", industry: "cybersecurity", hue: 12, progress: 85 },
    ],
  },
  {
    id: "cohort_2026b",
    name: "Cohort 2026-B",
    programName: "AI Track",
    startDate: "2026-09-01",
    companies: [
      { name: "Solstice Analytics", industry: "ai", hue: 168, progress: 12 },
      { name: "Pulsegrid", industry: "energy", hue: 42, progress: 8 },
    ],
  },
];
